"""Public Android SDK toolchain rule + provider.

The matching toolchain *type* is declared in `//rules/android:BUILD.bazel`
as `//rules/android:sdk_toolchain_type`. The `@android_sdk_toolchains`
repo (generated by the `android` extension) only emits the *instance*:

    android_sdk_toolchain(name = "sdk_tools", aapt2 = ..., zipalign = ..., ...)
    toolchain(
        name           = "sdk_toolchain",
        toolchain      = ":sdk_tools",
        toolchain_type = "//rules/android:sdk_toolchain_type",
    )

Keeping the type + rule alongside `extensions.bzl` (rather than templating
them into the generated repo) mirrors the convention a bazel_dep module
would use: its public API lives at stable in-module labels, and repo
rules only materialise the downloaded-artifact-bound instances.
"""

AndroidSdkToolchainInfo = provider(
    doc = "Android SDK build-time tools.",
    fields = {
        "aapt2": "File — aapt2 executable.",
        "zipalign": "File — zipalign executable.",
        "apksigner_jar": "File — apksigner.jar launched via `java -jar`.",
        "android_jar": "File — platform android.jar consumed by -I to aapt2.",
    },
)

def _android_sdk_toolchain_impl(ctx):
    return [platform_common.ToolchainInfo(
        sdktoolchaininfo = AndroidSdkToolchainInfo(
            aapt2 = ctx.file.aapt2,
            zipalign = ctx.file.zipalign,
            apksigner_jar = ctx.file.apksigner_jar,
            android_jar = ctx.file.android_jar,
        ),
    )]

android_sdk_toolchain = rule(
    implementation = _android_sdk_toolchain_impl,
    attrs = {
        "aapt2": attr.label(
            allow_single_file = True,
            cfg = "exec",
            executable = True,
            mandatory = True,
        ),
        "zipalign": attr.label(
            allow_single_file = True,
            cfg = "exec",
            executable = True,
            mandatory = True,
        ),
        "apksigner_jar": attr.label(
            allow_single_file = True,
            mandatory = True,
        ),
        "android_jar": attr.label(
            allow_single_file = True,
            mandatory = True,
        ),
    },
)
